name: build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: '5.x'
    - run: nuget restore PianoKeyboard.sln
    - uses: actions/upload-artifact@v2
      with:
        name: TestingRelease
        path: |
            src/PianoKeyboard/bin/**/*.exe